#!/bin/bash

# Towards SH1C
ip link set dev HALL-eth0 up
ip address add dev HALL-eth0 fd00:300:3:0f12::2/64

# Towards PYTH
ip link set dev HALL-eth1 up
ip address add dev HALL-eth1 fd00:300:3:0f23::2/64

#Lan
ip link set dev -lan0 up

ip link add link HALL-lan0 name HALL-lan0.120 type vlan id 0x120
ip link set dev HALL-lan0.120 up
ip address add dev HALL-lan0.120 fd00:300:3:120::/64

ip link add link HALL-lan0 name HALL-lan0.220 type vlan id 0x220
ip link set dev HALL-lan0.220 up
ip address add dev HALL-lan0.220 fd00:300:3:220::/64

ip link add link HALL-lan0 name HALL-lan0.420 type vlan id 0x420
ip link set dev HALL-lan0.420 up
ip address add dev HALL-lan0.420 fd00:300:3:420::/64

bird6 -s /tmp/HALL.ctl
