#!/bin/bash

# Towards SH1C
ip link set dev MICH-eth0 up
ip address add dev MICH-eth0 fd00:300:3:0f16::6/64

# Towards CARN
ip link set dev MICH-eth1 up
ip address add dev MICH-eth1 fd00:300:3:0f56::6/64

#Lan
ip link set dev MICH-lan0 up

ip link add link MICH-lan0 name MICH-lan0.160 type vlan id 0x160
ip link set dev MICH-lan0.160 up
ip address add dev MICH-lan0.160 fd00:300:3:160::/64

ip link add link MICH-lan0 name MICH-lan0.260 type vlan id 0x260
ip link set dev MICH-lan0.260 up
ip address add dev MICH-lan0.260 fd00:300:3:260::/64

ip link add link MICH-lan0 name MICH-lan0.460 type vlan id 0x460
ip link set dev MICH-lan0.460 up
ip address add dev MICH-lan0.460 fd00:300:3:460::/64

bird6 -s /tmp/MICH.ctl
